import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.KPT_BROWSER_MODULE || 'playwright');
const results = path.resolve('test-results');
await fs.mkdir(results, { recursive: true });
let server;
if (!process.env.KPT_PREVIEW_URL) {
  server = spawn(process.execPath, [fileURLToPath(new URL('../scripts/serve.mjs', import.meta.url))], { env: { ...process.env, PORT: '4174' }, stdio: ['ignore', 'pipe', 'pipe'] });
  await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); server.once('exit', code => { if (code) reject(new Error('Preview server could not start.')); }); });
}
const browser = await chromium.launch({ headless: true, ...(process.env.KPT_BROWSER_EXECUTABLE ? { executablePath: process.env.KPT_BROWSER_EXECUTABLE } : {}) });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = process.env.KPT_PREVIEW_URL || 'http://127.0.0.1:4174';
async function navigate(view) { await page.locator('[data-nav="' + view + '"]').click(); }
async function saveRecord() { await page.locator('#record-form button[type="submit"]').click(); await page.waitForFunction(() => !document.querySelector('#editor').open); }
try {
  await page.goto(base);
  await page.locator('#query').fill('Sample Member 001');
  await page.locator('#search-button').click();
  await page.getByRole('heading', { name: '1 member found', exact: true }).waitFor();
  assert.equal(await page.locator('.member-card').count(), 1);
  assert.equal(await page.locator('#search-mode option[value="ic"]').count(), 0);
  await page.screenshot({ path: path.join(results, 'public-desktop.png'), fullPage: true });
  await page.locator('#search-mode').selectOption('sjamId');
  await page.locator('#query').fill('010010');
  await page.locator('#search-button').click();
  await page.locator('.member-card .pill').filter({ hasText: 'Graduated' }).waitFor();
  await page.setViewportSize({ width: 375, height: 812 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(results, 'public-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(base + '/admin.html');
  await page.locator('.metric .value').first().waitFor();
  assert.equal(await page.locator('.metric .value').first().textContent(), '500');
  await page.screenshot({ path: path.join(results, 'admin-desktop.png'), fullPage: true });
  await navigate('Members');
  await page.locator('[data-action="add"][data-table="Members"]').click();
  await page.locator('#field-name').fill('Browser Test Student');
  await page.locator('#field-ic').fill('000000-01-0999');
  await page.locator('#field-form').fill('1');
  await saveRecord();
  await page.locator('#filter').fill('Browser Test Student');
  await page.getByRole('cell', { name: /Browser Test Student/ }).waitFor();
  assert.equal(await page.locator('tbody tr').count(), 1);
  await page.locator('[data-action="edit"]').click();
  await page.locator('#field-sjamId').fill('000999');
  await saveRecord();
  assert.equal(await page.getByRole('cell', { name: '000999', exact: true }).count(), 1);
  await navigate('Duty');
  await page.locator('#filter').fill('Browser Test Student');
  await page.locator('[data-action="duty"]').click();
  await page.locator('#field-hours').fill('60');
  await saveRecord();
  await page.getByRole('cell', { name: '60', exact: true }).waitFor();
  await navigate('Activities');
  await page.locator('[data-action="add"]').click();
  await page.locator('#field-name').fill('Browser Combined Activity');
  await page.locator('#field-date').fill('2026-10-08');
  await page.locator('input[name="tags"][value="Inspection"]').check();
  await page.locator('input[name="tags"][value="Exam"]').check();
  await page.locator('#field-examType').selectOption('BFA');
  await saveRecord();
  await page.locator('#filter').fill('Browser Combined Activity');
  await page.locator('[data-action="attendance"]').click();
  await page.locator('.roster label').filter({ hasText: 'Browser Test Student' }).locator('input').check();
  await page.locator('#attendance-form button[type="submit"]').click();
  await page.waitForFunction(() => !document.querySelector('#editor').open);
  await navigate('Exams');
  await page.locator('#filter').fill('Browser Test Student');
  await page.getByRole('cell', { name: 'Pending', exact: true }).waitFor();
  await page.locator('[data-action="edit"]').click();
  assert.equal(await page.locator('#field-attended').isChecked(), true);
  assert.equal(await page.locator('#field-attended').isDisabled(), true);
  await page.locator('#field-result').selectOption('Fail');
  await saveRecord();
  await page.getByRole('cell', { name: 'Fail', exact: true }).waitFor();
  await navigate('Awards');
  await page.locator('[data-action="add"]').click();
  await page.locator('#field-memberId').selectOption({ label: 'Browser Test Student · 000999' });
  await page.locator('#field-name').selectOption('First Aid Proficiency');
  await page.locator('#field-date').fill('2026-10-08');
  await saveRecord();
  await navigate('Import');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('[data-action="export"]').click();
  const download = await downloadPromise;
  const exportedPath = path.join(results, 'roundtrip.xlsx');
  await download.saveAs(exportedPath);
  await page.locator('#excel-file').setInputFiles(exportedPath);
  await page.locator('[data-action="previewImport"]').click();
  await page.getByText('0 proposed changes · 0 errors', { exact: true }).waitFor();
  await navigate('Settings');
  await page.locator('[data-action="backup"]').click();
  await page.getByText(/Private backup created/).waitFor();
  await page.locator('[data-action="listBackups"]').click();
  await page.locator('[data-action="restore"]').first().waitFor();
  page.once('dialog', dialog => dialog.accept());
  await page.locator('[data-action="restore"]').first().click();
  await page.getByText(/Records saved/).waitFor();
  await page.setViewportSize({ width: 375, height: 812 });
  await navigate('Overview');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(results, 'admin-mobile.png'), fullPage: true });
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: public search, alumni, mobile widths, member CRUD, Duty, multi-tag attendance, linked exams, awards, Excel round trip and restore.');
} finally { await browser.close(); if (server) server.kill(); }
