import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const domain = require('../src/domain.js');
const demo = require('../src/demo-data.js');
const read = name => fs.readFile(path.join(root, name), 'utf8');
const write = async (name, value) => { const target = path.resolve(root, name); if (!target.startsWith(root + path.sep)) throw new Error('Output is outside the project.'); await fs.mkdir(path.dirname(target), { recursive: true }); await fs.writeFile(target, value); };
const config = JSON.parse(await read('config.public.json'));
const publicKeys = ['organization', 'region', 'publicApiUrl', 'adminUrl', 'publicSiteUrl'];
if (Object.keys(config).some(key => !publicKeys.includes(key))) throw new Error('Public config has unsupported fields. Never add credentials.');
for (const key of ['adminUrl', 'publicApiUrl']) if (config[key] && !/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(config[key])) throw new Error('Use a Google /exec deployment URL for ' + key);
if (config.publicSiteUrl && !/^https:\/\/[\w.-]+\.github\.io\//.test(config.publicSiteUrl)) throw new Error('Use the GitHub Pages https URL for publicSiteUrl.');
const style = await read('src/styles.css');
const domainCode = await read('src/domain.js');
const workbook = await read('src/workbook.js');
const admin = await read('src/admin.js');
const library = await read('vendor/xlsx.full.min.js');
const libraryHash = crypto.createHash('sha256').update(library).digest('hex');
const expectedHash = (await read('vendor/SHA256.txt')).trim();
if (libraryHash !== expectedHash || !library.includes('0.20.3')) throw new Error('Excel vendor library checksum/version mismatch.');
const adminTemplate = await read('src/admin.html');
const inline = code => '<script>' + code.replace(/<\/script/gi, '<\\/script') + '</script>';
const transport = (await read('src/transport.js')).replace("'__PUBLIC_URL__'", JSON.stringify(config.publicSiteUrl || ''));
const productionAdmin = adminTemplate.replace('__STYLE__', '<style>' + style + '</style>').replace('__LIBRARY__', inline(library)).replace('__DOMAIN__', inline(domainCode)).replace('__WORKBOOK__', inline(workbook)).replace('__TRANSPORT__', inline(transport)).replace('__ADMIN__', inline(admin));
const previewAdmin = adminTemplate.replace('__STYLE__', '<link rel="stylesheet" href="styles.css">').replace('__LIBRARY__', '<script src="xlsx.full.min.js"></script>').replace('__DOMAIN__', '<script src="domain.js"></script>').replace('__WORKBOOK__', '<script src="workbook.js"></script>').replace('__TRANSPORT__', '<script src="demo-transport.js"></script>').replace('__ADMIN__', '<script src="admin.js"></script>');
for (const dir of ['dist', 'preview']) {
  await write(dir + '/index.html', await read('src/public.html'));
  await write(dir + '/public.js', await read('src/public.js'));
  await write(dir + '/styles.css', style);
  await write(dir + '/config.js', 'window.KPT_CONFIG = ' + JSON.stringify(dir === 'preview' ? { ...config, demo: true } : config).replace(/</g, '\\u003c') + ';\n');
}
await write('dist/.nojekyll', '');
await write('preview/admin.html', previewAdmin);
for (const file of ['domain.js', 'workbook.js', 'admin.js', 'demo-transport.js']) await write('preview/' + file, await read('src/' + file));
await write('preview/xlsx.full.min.js', library);
const fixture = demo.fixture(500, 2022, 2026);
domain.validateState(fixture);
await write('preview/demo-private.json', JSON.stringify(fixture));
await write('preview/demo-public.json', JSON.stringify(domain.projectPublic(fixture)));
await write('build/apps-script/admin/Admin.html', productionAdmin);
await write('build/apps-script/admin/Domain.gs', domainCode);
for (const project of ['admin', 'public']) for (const file of ['Code.gs', 'appsscript.json']) await write('build/apps-script/' + project + '/' + file, await read('apps-script/' + project + '/' + file));
const approvedFiles = ['.nojekyll', 'config.js', 'index.html', 'public.js', 'styles.css'];
const publicFiles = await fs.readdir(path.join(root, 'dist'));
if (publicFiles.some(name => !approvedFiles.includes(name))) throw new Error('Unexpected file in public dist. Review before publishing.');
console.log('Built public site, 500-member fictional preview, and two Google Apps Script deployment packages.');
console.log('Public deployment: dist/ · Local preview: preview/ · Google packages: build/apps-script/');
